# Generated by Django 4.0.4 on 2022-05-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('passwd', models.CharField(max_length=32)),
                ('no_of_employees', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('activity_status', models.BooleanField()),
                ('total_amount_donated', models.BigIntegerField()),
                ('cap_available', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NGOTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=256)),
                ('passwd', models.CharField(max_length=32)),
                ('no_of_employees', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('activity_status', models.BooleanField()),
                ('total_recd', models.BigIntegerField()),
                ('min_cap_reqd', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NGORep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincsr.ngotable')),
            ],
        ),
        migrations.CreateModel(
            name='CompRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincsr.companytable')),
            ],
        ),
    ]
