# Generated by Django 4.0.4 on 2022-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytable',
            name='activity_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companytable',
            name='company_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='companytable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companytable',
            name='phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='comprep',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='comprep',
            name='phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ngorep',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ngorep',
            name='phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='activity_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='ngo_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
