# Generated by Django 4.0.4 on 2022-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0002_alter_companytable_activity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytable',
            name='total_amount_donated',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='total_recd',
            field=models.BigIntegerField(default=0),
        ),
    ]
