# Generated by Django 4.0.4 on 2022-05-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0004_remove_companytable_passwd_remove_ngotable_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytable',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='comprep',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ngorep',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ngotable',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
