# Generated by Django 4.0.4 on 2022-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0008_alter_ngotable_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngotable',
            name='State',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ngotable',
            name='district',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
