# Generated by Django 4.0.4 on 2022-09-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0009_ngotable_state_ngotable_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngotable',
            old_name='State',
            new_name='state',
        ),
    ]
