# Generated by Django 4.0.4 on 2022-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0011_ngotable_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngotable',
            name='website',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
