# Generated by Django 4.0.4 on 2022-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0018_alter_ngotable_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngotable',
            name='pdf',
            field=models.FileField(null=True, upload_to='CSR-Project/Media/'),
        ),
    ]
