# Generated by Django 4.0.4 on 2022-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0020_alter_ngorep_fname_alter_ngorep_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngotable',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
