# Generated by Django 4.1.2 on 2022-10-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0007_alter_companytable_phone_alter_comprep_r_phone_and_more'),
        ('maincsr', '0021_alter_ngotable_pdf'),
    ]

    operations = [
    ]
