# Generated by Django 4.1.3 on 2022-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincsr', '0022_merge_20221030_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connid', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_name', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('initiator', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=20)),
                ('respdate', models.DateTimeField(null=True)),
                ('senddate', models.DateTimeField()),
            ],
        ),
    ]
